[package]
name = "network-scanner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hickory-client = "0.24"
rayon = "1.8"
tokio = { version = "1.13", features = ["full"] }
chrono = "0.4"
